### ISSUE TITLE
Response 255 for Garry's Mod Servers

### ISSUE THREAD

**Issue by berkbuzcu** [Yepoleb/python-a2s#6]
Hello, I don't see a format so here we go:

I get the parse error for Garry's Mod servers when I call the players() method with the code 255.

I have managed to work around this problem by disabling the check and reading the first uint32, then all the players were retrieved.

Below you can find the hack, I don't know how to fix this issue permanently.

```
    #if response_type != A2S_PLAYER_RESPONSE:
    #    raise BrokenMessageError(
    #        "Invalid response type: " + str(response_type))

    reader.read_uint32()
```

Right at L:48 of players.py

**Comment by Yepoleb** [comment]
Great report, I'll look into it as soon as possible.

**Comment by Yepoleb** [comment]
Hm, I've managed to reproduce the issue, but the official Steam client complains about such servers as well. Not sure how to deal with this, the response is most likely corrupted and should be fixed on the server side.

**Comment by berkbuzcu** [comment]
Seems to be that way, but the corrupt message can be cleaned by reading the first bytes, I have no idea why.

And sometimes the error persists despite reading the bytes, so I guess a solution could be to read bytes until the message works? 

Well of course I mean as a hack, not as a permanent solution. Something people can use meanwhile.

**Comment by Yepoleb** [comment]
A special branch just for this issue? I guess that would work.

**Comment by Yepoleb** [comment]
I've tried to reproduce this issue now on two separate days and can no longer find servers with this bug. Do you have an address for me that's still broken?

**Comment by berkbuzcu** [comment]
Sorry for the late response,

Unfortunately I stopped using the API since the need is over but it occured to me today that it might have been related to large servers with unusual player counts, ie nebulous cloud.

Good luck!

**Comment by Yepoleb** [comment]
Thanks for your response, sorry I wasn't able to help in time :frowning:. Best of luck to you as well!
